Google Auth #5
CESARBR/corona-mission pull request #20
Opened 2020-04-01 21:10 UTC by vieira-rodrigo

Performing google authentication.

2020-04-01 22:07 UTC, vcasadei requested changes
The Google auth works.

However, if I try to create an account with the same Email as I used in the login google auth, the app breaks. Could you check this?

2020-04-02 13:35 UTC, vieira-rodrigo commented
> The Google auth works.
> 
> However, if I try to create an account with the same Email as I used in the login google auth, the app breaks. Could you check this?

Done.

2020-04-02 13:40 UTC, vcasadei requested changes

2020-04-02 13:40 UTC, vcasadei commented on src/app/pages/login/login.page.ts
> +      this.coronaToast.showError("Could not perform authetication.");
Colocar em pt-br

2020-04-02 13:40 UTC, vcasadei commented on src/app/pages/signup/signup.page.ts
> +        let msg = error.code == 'auth/email-already-in-use' ? 'The email address is already in use' : error.message
pt-br

2020-04-02 13:54 UTC, vcasadei approved these changes
It works!

2020-04-02 13:54 UTC, merged